Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DiscGolf.Models;

namespace DiscGolf.Areas.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private GamesPlayedUnitOfWork data { get; set; }
        public HomeController(DiscGolfContext ctx) => data = new GamesPlayedUnitOfWork(ctx);

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PlayerList()
        {
            var playerOptions = new QueryOptions<Player>
            {
                OrderBy = d => d.Name
            };
            return View(data.Players.List(playerOptions));
        }
        public IActionResult CourseList()
        {
            var holeOptions = new QueryOptions<Hole>
            {
                Includes = "Course"
            };
            var courseOptions = new QueryOptions<Course>
            {
                OrderBy = d => d.CourseName
            };
            ViewBag.Holes = data.Holes.List(holeOptions);
            return View(data.Courses.List(courseOptions));
        }
        public IActionResult GamePlayedList()
        {
            var gameOptions = new QueryOptions<GamePlayed>
            {
                Includes = "Player, Course",
                Where = d => d.GameFinished != false,
                OrderBy = d => d.Course.CourseName,
                ThenOrderBy = d => d.Score
            };
            var openGameOptions = new QueryOptions<GamePlayed>
            {
                Includes = "Player, Course",
                Where = d => d.GameFinished != true,
                OrderBy = d => d.Course.CourseName,
                ThenOrderBy = d => d.Score
            };
            var playerOptions = new QueryOptions<Player> { };
            ViewBag.Players = data.Players.List(playerOptions);
            ViewBag.OpenGames = data.GamesPlayed.List(openGameOptions);
            ViewBag.Holes = data.Holes.List(new QueryOptions<Hole> { });
            return View(data.GamesPlayed.List(gameOptions));
        }

        [HttpGet]
        public IActionResult DeletePlayer(int id)
        {
            return View(data.Players.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult DeletePlayer(Player p)
        {
            data.Players.Delete(p);
            data.Players.Save();
            return RedirectToAction("PlayerList");
        }

        [HttpGet]
        public IActionResult EditPlayer(int id)
        {
            return View(data.Players.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult EditPlayer(Player p)
        {
            data.Players.Update(p);
            data.Players.Save();
            return RedirectToAction("PlayerList");
        }

        [HttpGet]
        public IActionResult DeleteCourse(int id)
        {
            return View(data.Courses.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult DeleteCourse(Course c)
        {
            data.Courses.Delete(c);
            data.Courses.Save();
            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult AddCourse()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCourse(Course course)
        {
            data.Courses.Insert(course);
            data.Courses.Save();
            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult EditCourse(int id)
        {
            ViewBag.Holes = data.Holes.List(new QueryOptions<Hole>
            {
                Includes = "Course",
                Where = h => h.CourseID == id,
                OrderBy = h => h.SequenceNumber
            });
            return View(data.Courses.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult EditCourse(Course c)
        {
            data.Courses.Update(c);
            data.Courses.Save();
            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult ViewCourse(int id)
        {
            ViewBag.Holes = data.Holes.List(new QueryOptions<Hole>
            {
                Includes = "Course",
                Where = h => h.CourseID == id,
                OrderBy = h => h.SequenceNumber
            });
            return View(data.Courses.Get(id));
        }

        [HttpGet]
        public IActionResult DeleteHole(int id)
        {
            ViewBag.Courses = data.Courses.List(new QueryOptions<Course> { });
            return View(data.Holes.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult DeleteHole(Hole h)
        {
            data.Holes.Delete(h);
            data.Holes.Save();
            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult AddHole()
        {
            ViewBag.Courses = data.Courses.List(new QueryOptions<Course>
            {
                OrderBy = c => c.CourseName
            });
            return View();
        }
        [HttpPost]
        public IActionResult AddHole(Hole hole)
        {
            data.Holes.Insert(hole);
            data.Holes.Save();
            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult EditHole(int id)
        {
            ViewBag.Courses = data.Courses.List(new QueryOptions<Course> { });
            return View(data.Holes.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult EditHole(Hole h)
        {
            data.Holes.Update(h);
            data.Holes.Save();
            return RedirectToAction("CourseList");
        }

        [HttpGet]
        public IActionResult DeleteGamePlayed(int id)
        {
            return View(data.GamesPlayed.Get(id));
        }
        [HttpPost]
        public RedirectToActionResult DeleteGamePlayed(GamePlayed gp)
        {
            data.GamesPlayed.Delete(gp);
            data.GamesPlayed.Save();
            return RedirectToAction("GamePlayedList");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DiscGolf.Models;
using System.Net;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace DiscGolf.Controllers
{
    public class HomeController : Controller
    {
        private GamesPlayedUnitOfWork data { get; set; }
        public HomeController(DiscGolfContext ctx) => data = new GamesPlayedUnitOfWork(ctx);

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Info()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            TempData["Incorrect"] = "";
            return View("Login");
        }

        [HttpPost]
        public IActionResult Login(Player player)
        {
            var playerOptions = new QueryOptions<Player>
            {
                OrderBy = d => d.Name
            };
            var players = data.Players.List(playerOptions);
            foreach (Player p in players)
            {
                if (player.Username == p.Username)
                {
                    if (player.Password == p.Password)
                    {
                        if(p.Name == "Admin")
                        {
                            return RedirectToAction("Index", "Home", new { Area = "Admin" });
                        }
                        List<GamePlayed> playerGames = new List<GamePlayed>();
                        List<GamePlayed> playerOpenGames = new List<GamePlayed>();
                        List<Course> allPlayedCourses = new List<Course>();
                        List<Course> allPlayerOpenCourses = new List<Course>();
                        List<int?> coursePar = new List<int?>();
                        List<int?> openCoursePar = new List<int?>();
                        var gameOptions = new QueryOptions<GamePlayed>
                        {
                            OrderBy = gp => gp.Score,
                            Where = gp => gp.GameFinished == true
                        };
                        var courseOptions = new QueryOptions<Course>
                        {
                            OrderBy = c => c.CourseName
                        };
                        var openCourseOptions = new QueryOptions<Course>
                        {
                            OrderBy = c => c.CourseName
                        };
                        var openGameOptions = new QueryOptions<GamePlayed>
                        {
                            Where = gp => gp.GameFinished == false,
                            OrderBy = gp => gp.GamePlayedID
                        };
                        var games = data.GamesPlayed.List(gameOptions);
                        var openGames = data.GamesPlayed.List(openGameOptions);
                        var courses = data.Courses.List(courseOptions);
                        var openCourses = data.Courses.List(openCourseOptions);
                        foreach (GamePlayed game in games)
                        {
                            if (game.PlayerID == p.PlayerID)
                            {
                                playerGames.Add(game);
                                foreach (Course c in courses)
                                {
                                    if (game.CourseID == c.CourseID)
                                    {
                                        if (allPlayedCourses.Contains(c) == false)
                                        {
                                            allPlayedCourses.Add(c);
                                            var holeOptions = new QueryOptions<Hole>
                                            {
                                                Where = h => h.CourseID == c.CourseID
                                            };
                                            var holes = data.Holes.List(holeOptions);
                                            int? par = 0;
                                            foreach (Hole h in holes)
                                            {
                                                par += h.Par;
                                            }
                                            coursePar.Add(par);
                                        }
                                    }
                                }
                            }
                        }
                        foreach(GamePlayed openGame in openGames)
                        {
                            if(openGame.PlayerID == p.PlayerID)
                            {
                                playerOpenGames.Add(openGame);
                            }
                            foreach(Course course in openCourses)
                            {
                                if(course.CourseID == openGame.CourseID)
                                {
                                    if(allPlayerOpenCourses.Contains(course) == false)
                                    {
                                        allPlayerOpenCourses.Add(course);
                                        var holeOptions = new QueryOptions<Hole>
                                        {
                                            Where = h => h.CourseID == course.CourseID
                                        };
                                        var holes = data.Holes.List(holeOptions);
                                        int? par = 0;
                                        foreach (Hole h in holes)
                                        {
                                            par += h.Par;
                                        }
                                        openCoursePar.Add(par);
                                    }
                                }
                            }
                        }
                        TempData["OpenGames"] = playerOpenGames;
                        TempData["Games"] = playerGames;
                        TempData["Courses"] = allPlayedCourses;
                        TempData["Pars"] = coursePar;
                        TempData["Player"] = p;
                        TempData["OpenCourses"] = allPlayerOpenCourses;
                        TempData["OpenCoursePar"] = openCoursePar;
                        return View("../Player/Index");
                    }
                }
                
            }
            TempData["Incorrect"] = "Incorrect Login";
            return View("Login");
        }

        [HttpGet]
        public IActionResult Register()
        {
            ViewBag.Action = "Add";
            return View("Register", new Player());
        }

        [HttpPost]
        public IActionResult Register(Player player)
        {
            if (ModelState.IsValid)
            {
                if (player.PlayerID == 0)
                    data.Players.Insert(player);
                    data.Players.Save();
                return RedirectToAction("Login", "Home");
            }
            else
            {
                return View("Index");
            }
        }
    }
}

Controllers/LeaderBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DiscGolf.Models;

namespace DiscGolf.Controllers
{
    public class LeaderBoardController : Controller
    {
        private GamesPlayedUnitOfWork data { get; set; }
        public LeaderBoardController(DiscGolfContext ctx) => data = new GamesPlayedUnitOfWork(ctx);

        public IActionResult Index()
        {
            var courseOptions = new QueryOptions<Course>
            {
                OrderBy = c => c.CourseName
            };
            var gameOptions = new QueryOptions<GamePlayed>
            {
                Includes = "Player, Course",
                OrderBy = gp => gp.GamePlayedID,
                Where = gp => gp.GameFinished == true
            };

            var games = data.GamesPlayed.List(gameOptions);
            var courses = data.Courses.List(courseOptions);
            List<GamePlayed> finalGames = new List<GamePlayed>();
            List<int?> coursePar = new List<int?>();

            foreach (Course c in courses)
            {
                var holeOptions = new QueryOptions<Hole>
                {
                    Where = h => h.CourseID == c.CourseID
                };
                var holes = data.Holes.List(holeOptions);
                int? par = 0;
                foreach (Hole h in holes)
                {
                    par += h.Par;
                }
                coursePar.Add(par);
                var lowScore = 101;
                List<GamePlayed> bestGames = new List<GamePlayed>();
                foreach (GamePlayed gp in games)
                {
                    if (gp.CourseID == c.CourseID)
                    {
                        if (gp.Score < lowScore)
                        {
                            lowScore = gp.Score;
                            bestGames.Clear();
                            bestGames.Add(gp);
                        }
                        else if(gp.Score == lowScore)
                        {
                            bestGames.Add(gp);
                        }
                    }
                }
                foreach (GamePlayed gp in bestGames)
                    finalGames.Add(gp);
            }

            TempData["Courses"] = courses;
            TempData["Pars"] = coursePar;

            return View(finalGames);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<a asp-controller="Home" asp-action="Login" class="btn btn-primary">Login/Register</a>
<a asp-controller="LeaderBoard" asp-action="Index" class="btn btn-secondary">Leaderboards</a>
<a asp-controller="Home" asp-action="Info" class="btn btn-secondary">More Info</a>

Views/Home/Info.cshtml
@{
    ViewData["Title"] = "Info Page";
}

<div class="text-center">
    <h2 class="text-center">Game Overview</h2>
    <p class="text-left">
        Disc Golf is a simple sport to get into but difficult to master. The game will
        take you on a course through a series of holes. You start from inside the tee-box
        on each hole and make your best throw towards the basket/goal. The disc must come to
        rest in the basket for you to complete each hole. Like golf, the lower your score, the
        better.
    </p>
    <h2 class="text-center">Rules</h2>
    <p class="text-left">
        The general rules of disc golf are simple: You must start from inside the
        tee-box, the disc must come to rest inside the basket, and for throws while on the course, your
        planting foot must be behind where your disc came to lie. When playing with others, the furthest from the
        basket throws first after everyone has thrown once. More detailed rules can be found at the disc golf website,
        under <a href="https://discgolf.com/disc-golf-education-development/disc-golf-rules-for-recreational-play/">recreational rules</a>.
    </p>
    <h2 class="text-center">This Site</h2>
    <p class="text-left">
        This site was created to help the player track their games across several courses. 
        The courses are added by the admin. If a course is not added and you would like to see it added, 
        contact a site administrator. All of your games will show up under the courses you played on when you log in. 
        Any open games, games you have not finished, are shown towards the bottom of your homepage. Those games can be completed 
        anytime if you want to go back to the course and continue you game or cancelled if you don’t have the opportunity to 
        finish the game. If you want to play with a friend, add them to your game with the “add player” button when you select 
        “play game”. They must be registered through the site (registration can be found on the homepage and is super simple).
    </p>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Home</a>
</div>

Views/Home/Login.cshtml
@model Player
@{
    ViewData["Title"] = "Login Page";
    string incorrectLogin = TempData["Incorrect"] as string;
}

@if(incorrectLogin != "")
{
    <p class="text-danger">@TempData["Incorrect"]</p>
}
<form asp-action="Login" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Username">Username: </label>
        <input asp-for="Username" class="form-control col-sm-4" />
    </div>
    <div class="form-group">
        <label asp-for="Password">Password: </label>
        <input asp-for="Password" class="form-control col-sm-4" type="password"/>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
<p></p>
<a asp-controller="Home" asp-action="Register" class="btn btn-secondary">Register</a>
<a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Home</a>

Views/Home/Register.cshtml
@model Player
@{
    ViewData["Title"] = "Register Page";
}

<form asp-action="Register" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name">Name: </label>
        <input asp-for="Name" class="form-control col-sm-4" />
    </div>
    <div class="form-group">
        <label asp-for="Username">Username: </label>
        <input asp-for="Username" class="form-control col-sm-4" />
    </div>
    <div class="form-group">
        <label asp-for="Password">Password: </label>
        <input asp-for="Password" class="form-control col-sm-4" />
    </div>
    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-controller="Home" asp-action="Login" class="btn btn-primary">Cancel</a>
</form>